### ISSUE TITLE
Availability of final dataset

### ISSUE THREAD

**Issue by timoast** [Henikoff/scCUT-Tag#3]
Hi, could the final processed matrix for each PBMC dataset and their annotated cell types be made available? I couldn't find this in the paper supplement or on GEO, apologies if it's already available and I missed it somewhere.

**Comment by Henikoff** [comment]
Hello, your request has been forwarded to Dr. Scott Furlan, ***@***.*** .
-Jorja Henikoff

________________________________________
From: Tim Stuart ***@***.***>
Sent: Friday, May 6, 2022 12:45 PM
To: Henikoff/scCUT-Tag
Cc: Subscribed
Subject: [Henikoff/scCUT-Tag] Availability of final dataset (Issue #3)

Hi, could the final processed matrix for each PBMC dataset and their annotated cell types be made available? I couldn't find this in the paper supplement or on GEO, apologies if it's already available and I missed it somewhere.

**Comment by scfurl** [comment]
Hi Tim,  I am attaching here but will have a link to it added to the readme for others.  Best
[meta.csv](https://github.com/Henikoff/scCUT-Tag/files/8647406/meta.csv)

**Comment by timoast** [comment]
@scfurl thanks so much!

**Comment by timoast** [comment]
Hi @scfurl does this file contain the H3K27ac cell metadata as well? In the "Sample" column, I see pbmc2_CNT1 and pbmc2_CNT2 which I'm assuming correspond to healthy PBMC H3K27me3 replicate 1 and 2?

**Comment by scfurl** [comment]
Hi @timoast.  Sorry, no It doesn't, just K27me3.  Will have to dig that up...

**Comment by scfurl** [comment]
@timoast.  Here are the 27Ac metadata for PBMC
[K27Ac_pbmc_meta.csv](https://github.com/Henikoff/scCUT-Tag/files/8653804/K27Ac_pbmc_meta.csv)
.

**Comment by timoast** [comment]
Thanks!
